branches:
  only: 
    - master
matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "8"
      script: 
        - cd src && npm run ci.tslint
        - cd ../demo && npm run ci.tslint
        - cd ../demo-angular && npm run ci.tslint
    - stage: "WebPack, Build and Test"
      os: osx
      env:
        - WebpackiOS="12"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_script: pod repo update
      script: 
        - cd src && npm run build.iosOnly
        - cd ../demo && npm i && tns build ios --env.uglify
        - cd ../demo-angular && npm i && tns build ios --env.uglify --env.aot
    - language: android
      os: linux
      env:
        - WebpackAndroid="28"
      jdk: oraclejdk8
      before_install: nvm install 8
      script:
        - cd src && npm run build && cd ../demo && npm i && tns build android --env.uglify --env.snapshot
        - cd ../demo-angular && npm i && tns build android --env.uglify --env.snapshot --env.aot
    - language: android
      env: 
        - BuildAndroid="28"
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 8
      script: 
        - cd demo && npm run ci.android.build
        - cd ../demo-angular && npm run ci.android.build
    - os: osx
      env: 
        - BuildiOS="12"
        - Xcode="10.0"
      osx_image: xcode10.0
      language: node_js 
      node_js: "8"
      jdk: oraclejdk8
      before_script: pod repo update
      script: 
        - cd demo && npm run ci.ios.build
        - cd ../demo-angular && npm run ci.ios.build

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

before_install:
  - sudo pip install --upgrade pip
  - sudo pip install six

install:
    - echo no | npm install -g nativescript
    - echo no | npm install -g typescript
    - tns usage-reporting disable
    - tns error-reporting disable
    
